services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
      - 8502:8502
    volumes:
      - .:/app
      # Mount the Docker socket to allow the backend to interact with Docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - frontend
